name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
            
    - uses: azure/docker-login@v1
      with:
        login-server: ryoshiga.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker Build
      run:  docker build . -t ryoshiga.azurecr.io/ryoshigagoapi:${{ github.sha }}

    - name: Docker push
      run:  docker push ryoshiga.azurecr.io/ryoshigagoapi:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'ryoshiga-go-api'
        images: 'ryoshiga.azurecr.io/ryoshigagoapi:${{ github.sha }}'
        slot-name: 'production'
            
    #--build-arg instrumentation_key=${{ secrets.INSTRUMENTATION_KEY }} --build-arg app_insights_api_key=${{ secrets.APP_INSIGHTS_API_KEY }}
    
